# .github/workflows/deploy.yml
name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          echo "Deploying to production"

    # steps:
    #   - uses: actions/checkout@v2

    #   - name: Use Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '18'

    #   - name: Install dependencies
    #     run: npm ci

    #   - name: Build
    #     run: npm run build

    #   - name: Generate deployment package
    #     run: zip -r deploy.zip . -x '*.git*'

    #   - name: Deploy to EB
    #     uses: einaregilsson/beanstalk-deploy@v20
    #     with:
    #       aws_access_key: ${{ secrets.SBD_AWS_ACCESS_KEY_ID }}
    #       aws_secret_key: ${{ secrets.SBD_AWS_SECRET_ACCESS_KEY }}
    #       application_name: your-app-name
    #       environment_name: your-environment-name
    #       version_label: ${{ github.sha }}
    #       region: us-east-1
    #       deployment_package: deploy.zip
